version: "3.8"

services:
  twttr-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: twttr-frontend
    ports:
      - 8080:4173
    restart: always
    volumes:
      - .:/app