version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: api
    depends_on:
      - psql
      - redis
    ports:
      - 5000:5000
    restart: always
    volumes:
      - .:/usr/src/app/
    command: python manage.py

  psql:
    container_name: psql
    image: postgres:14.8
    env_file:
      - .env
    ports:
      - 5433:5432
    restart: always
    volumes:
      - data-psql:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7.2
    ports:
      - 6379:6379
    restart: always

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: celery-worker
    command: celery -A make_celery worker --loglevel=info
    depends_on:
      - redis
    restart: always
    volumes:
      - .:/usr/src/app/

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: celery-beat
    command: celery -A make_celery beat --loglevel=info
    depends_on:
      - celery-worker
    restart: always
    volumes:
      - .:/usr/src/app/

volumes:
  data-psql: