version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: api
    depends_on:
      - psql
    ports:
      - 5000:5000
    restart: always
    volumes:
      - .:/usr/src/app/
    command: python manage.py

  psql:
    container_name: psql
    image: postgres:14.8
    env_file:
      - .env
    ports:
      - 5433:5432
    restart: always
    volumes:
      - data-psql:/var/lib/postgresql/data

volumes:
  data-psql: