version: "3.8"

services:
  twttr-api:
    image: thujuli/twttr-backend:latest
    env_file:
      - .env
    container_name: twttr-api
    depends_on:
      - psql
      - redis
    ports:
      - 5000:8000
    restart: always
    command: gunicorn -w 4 --bind 0.0.0.0:8000 "app:create_app()"

  psql:
    container_name: psql
    image: postgres:14.8
    env_file:
      - .env
    ports:
      - 5433:5432
    restart: always
    volumes:
      - data-psql:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7.2
    ports:
      - 6379:6379
    restart: always

  celery-worker:
    image: thujuli/twttr-backend:latest
    env_file:
      - .env
    container_name: celery-worker
    command: celery -A make_celery worker --loglevel=info
    depends_on:
      - redis
    restart: always

  celery-beat:
    image: thujuli/twttr-backend:latest
    env_file:
      - .env
    container_name: celery-beat
    command: celery -A make_celery beat --loglevel=info
    depends_on:
      - celery-worker
    restart: always

volumes:
  data-psql:
